### ISSUE TITLE
simpleWeather is currently not working.

### ISSUE THREAD

**Issue by DukeBaird** [monkeecreate/jquery.simpleWeather#174]
Possible duplicate of open issue, but simpleweather sometimes errors and calls no callbacks.

```jquery.simpleWeather.min.js:2 Uncaught TypeError: Cannot read property 'channel' of null```

However, its not triggering the error function on the original query

```
$.simpleWeather({
					location: 'Waterloo',
					woeid: '',
					unit: 'c',
					success: function(weather) {
						$("#curTemp").html("Outdoor Weather: " + weather.temp + "°C, " + weather.currently);
					},
					error: function(error) {
						$('#curTemp').html("Could not get Weather data");
					}
```

Is there a way to make it call the error callback if this occurs?

**Comment by ds00424** [comment]
I am having similar issue.
Looks like Yahoo is returning a Service Unavailable message at the moment.
I assume this is the trigger for the problem.

Query:
https://query.yahooapis.com/v1/public/yql?format=json&rnd=20160214&diagnostics=true&callback=jQuery211031334247775704394_1453233474635&q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.placefinder%20where%20text=%2207722%22%20and%20gflags=%22R%22%20limit%201)%20and%20u=%22f%22&_=1453233474636

Response:
/**/jQuery211031334247775704394_1453233474635({"query":{"count":0,"created":"2016-01-19T19:57:40Z","lang"
:"en-US","diagnostics":{"publiclyCallable":"true","url":{"execution-start-time":"1","execution-stop-time"
:"5","execution-time":"4","http-status-code":"503","http-status-message":"Service Unavailable","content"
:"http://gws2.maps.yahoo.com/findlocation?pf=1&locale=en_US&offset=15&flags=&q=07722&gflags=R&start=0
&count=100"},"user-time":"7","service-time":"4","build-version":"0.2.376"},"results":null}});

As noted in the issue report, neither the success nor the error callbacks are called.
HTH.

**Comment by felixdorner** [comment]
Same here...

**Comment by nickels55** [comment]
Same here - I tweeted @fleetingftw to make sure he is aware of the issue.

**Comment by rachelicha** [comment]
Same here. I also tweeted around an hour ago. Although based on ds00424's message, the error is potentially with Yahoo.

**Comment by ryotasolar** [comment]
how come the yahoo weather api is working fine but not with this?

**Comment by MuhammadSaleh** [comment]
same here !

**Comment by oasif** [comment]
to fix edit jquery.simpleWeather.js
remove  
and gflags="R" limit 1 
from line 26

**Comment by MuhammadSaleh** [comment]
worked .. thanks @oasif

**Comment by ryotasolar** [comment]
wow that worked. I would of never guessed this. thanks @oasif

**Comment by conntagious** [comment]
Thanks @oasif!

**Comment by ctrlaltdylan** [comment]
Thank you @oasif !!!

Put the fix in a fork of the library and PR'd, although I'm not sure how to recreate the minified version.

https://github.com/ctrlaltdylan/jquery.simpleWeather

**Comment by ds00424** [comment]
Thank you @oasif.
i don't know yql, but briefly looking at the docs, looks like gflags was previously used for geolocation using lat, lon.  I guess something changed very recently to remove gflags.  "Service Unavailable" from yql was a bit misleading.
i am not sure why the weather yql was using it in the first place (didn't look necessary for zip code lookup).
Did the "limit 1" have any effect?  Leaving it in seemed ok as well.  Although in some brief testing with yql console, I never got multiple results.

This fix ought to be included in v3.0.3.
Also a call to the error callback on this type of condition in the future.

**Comment by VitalyNikolaev** [comment]
Removing 
and gflags="R" limit 1 
from line 26
bring me to [Object][Object] . error: "City not found".

**Comment by BonnieDoug** [comment]
Same issue as VitalyNikolaev here...

**Comment by ascott23** [comment]
@VitalyNikolaev I was having the same problem. I fixed it by adding [0] to the end of data.query.results.channel on line 38 or leaving the limit 1 in on line 26

**Comment by fleeting** [comment]
`limit 1` is encouraged to leave as is due to several places returning multiple locations.

**Comment by ascott23** [comment]
I've now started having problems again using geolocation, it seems like using city works but not lat and long. Can anyone else test and confirm this?

**Comment by VitalyNikolaev** [comment]
Yes, and solutions above, dosent solve the problem

**Comment by ascott23** [comment]
@VitalyNikolaev It's weird because it seemed to last night and when I wrote my last post...?

**Comment by oasif** [comment]
The following line 26 should work with zip code:
weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+options.location+'") and u="'+options.unit+'"';

**Comment by ascott23** [comment]
I (and I believe a few other people) are wanting to use the lat and long (as we can easily get it dynamically) so zip codes etc. don't work as well

**Comment by fleeting** [comment]
Correct, currently it's the lat/long that is causing the issue. Yahoo's API is reporting service unavailable on looking up location data using lat/long. Removing the `gflags="R"` will give a temporary work around for zip code and city, state in the location param. The `gflags` is there just to do a reverse lookup when querying with lat/long. I've verified using the examples Yahoo provides in their documentation that their reverse lat/long lookup is currently down. simpleWeather isn't the only script affected based on a quick [stackoverflow search](http://stackoverflow.com/questions/34898062/yql-api-to-get-city-state-code-from-lat-long-is-returning-null). The best solution is the temp fix of removing `gflags` if you are using zip code or city/state as location and hopefully Yahoo restores the reverse lookup API.

**Comment by ascott23** [comment]
@fleeting Is there an official place to check the status of that part of the api so I can figure out when the service is back up?

**Comment by fleeting** [comment]
@ascott23 Not that I'm aware of. Info and support from Yahoo regarding their APIs is rare. They post in their forums pretty rare and there are a few topics already open on it from other people about the issue ([one](https://developer.yahoo.com/forums/#/discussion/7840/yql-api-to-get-city-state-code-from-lat-long-is-returning-nul%3D), [two](https://developer.yahoo.com/forums/#/discussion/7834/why-did-the-database-change%3D)). Their weather API went down a little while back and it took several days before it came back up with very little word from them besides on the [uservoice](https://yahoo.uservoice.com/forums/207813-us-weather) page.

**Comment by ascott23** [comment]
@fleeting Ok thanks! 
I've found a work-around for now with google's API which gets the city and province names (for canada at least) [here](http://pastebin.com/s0sU0fMH)
Based off this stackoverflow [post](https://stackoverflow.com/questions/6797569/get-city-name-using-geolocation) and using the docs [here](https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingResults)

**Comment by fleeting** [comment]
Workarounds are always a pain but I'm going to finally look for a replacement API. Yahoo has been pretty unreliable the past six months, next to zero support/response, and generally lacks some weather data people ask for often. I've got a few I'll be checking out.

**Comment by ascott23** [comment]
Keep up the awesome work!

**Comment by nickels55** [comment]
Thanks for the update and suggested fixes! @oasif suggestion about removing that code from line 26 worked for me.

**Comment by wmoore** [comment]
Here is a workaround that supports lat/lng and text locations.

**Warning: The Weather Underground geolookup call returns a warning that it will be depreciated.  This is a temporary workaround.**

Replace line 26 with this -
```
if(options.location.match(/^([-+]?\d{1,2}([.]\d+)?),\s*([-+]?\d{1,3}([.]\d+)?)$/)) {
  weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.placefinder where text in (select city from wunderground.geolookup where location="'+options.location+'" limit 1) limit 1) and u="'+options.unit+'"&env=store://datatables.org/alltableswithkeys';          
} else {
  weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.placefinder where text="'+options.location+'" limit 1) and u="'+options.unit+'"';
}
```

**Comment by VitalyNikolaev** [comment]
Thank you! Worked for me!

**Comment by balazsegyed** [comment]
@wmoore  It's worked for a while  but it semms to be not working now.

**Comment by rysie** [comment]
Seems that geo.placefinder table is not working anymore. I've just checked the following solution and it's working perfectly for me:

Line #26:
weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';

**Comment by quartsZzz** [comment]
Thank you, it works.

**Comment by VitalyNikolaev** [comment]
I have got Cannot read property 'channel' of null, can you provide 24-30 lines, please? I think i got something wrong

**Comment by cjingle** [comment]
rysie answer worked for me.  Thanks.

**Comment by TerrenceLP** [comment]
This temp fix is not working - Just tried the remove Gflags... still channel error - 

Looking like a way to pick from a few api sources may be the way top have some fall back.

TO THE DEVELOPER - What Can I do To Help? Point Me in the direction you need help with but where time hasn't been available. I'll see what I can do.

**Comment by joejoe9982** [comment]
Won't work with lat/long. Any solution with long/lat?

**Comment by balazsegyed** [comment]
I fint a temporary solution for geoloc:
```javascript    
$.getJSON('http://ipinfo.io', function(data){
	var location=data.city+', '+data.country;
	loadWeather(location);
});
```
This is a geolocation service from IP.

**Comment by andretf** [comment]
Yahoo's problem. Using YQL isn't working at all with geo.placefinder:
https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.placefinder%20where%20text%3D%2210005%22&format=json&diagnostics=true&format=json

but direct call does work:
http://gws2.maps.yahoo.com/findlocation?pf=1&locale=en_US&offset=15&flags=&q=10005&gflags=R&start=0&count=1&format=json

rysie solution works perfectly right now.

**Comment by andretf** [comment]
for rsye solution work with latitude/longitude, surround "option.location" value with parenthesis. E.g. 

    $.simpleWeather({
        location: '(' + lat + ',' + long + ')',
        ...

https://developer.yahoo.com/yql/console/#h=select+woeid+from+geo.places+where+text%3D%22(-30.0318168%2C-51.1860499)%22+limit+1

**Comment by VitalyNikolaev** [comment]
could someone make Line #26 correct for geolocation?

**Comment by balazsegyed** [comment]
Geoloc by @andretf  answer, working fine, thanks.

//geoloc coordinates long/lat
navigator.geolocation.getCurrentPosition(function(position) {
    loadWeather(position.coords.latitude, position.coords.longitude); 
  });

//call simpleweather
function loadWeather(location, woeid) {
  $.simpleWeather({
    location: '(' + location + ',' + woeid + ')',
    woeid: "",
    ...

**Comment by bluesunlite** [comment]
@VitalyNikolaev:
For me it worked with getting rid of this little part " and gflags="R" " in line 26. So line 26 should look like this:  weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.placefinder where text="'+options.location+'" limit 1) and u="'+options.unit+'"';

Then you need to do some changes in your javascript. The following is working for me:

<script type="text/javascript">
$(document).ready(function() {
  $.simpleWeather({
    woeid: '766356',
    unit: 'c',
    success: function(weather) {
      html =  '<img style= width="21px" height="21px" src="fileadmin/tiempo/tiempoiconos/'+weather.code+'.png">'+'<div class="wetterzahl">'+weather.temp+'&deg;'+weather.units.temp+'</div>';
      $("#testweather").html(html);
    },
    error: function(error) {
      $("#testweather").html('<p>'+error+'</p>');
    }
  });
});
</script>

And embedding like this:
<div class="tiempform">Weather:</div><div id="testweather"></div>

Good luck ;)

**Comment by VitalyNikolaev** [comment]
Thank you guys, its finally worked

**Comment by robschwartz** [comment]
@VitalyNikolaev what was your final solution? I have tried a couple posted but none have worked yet.

**Comment by VitalyNikolaev** [comment]
25-32 of simpleweather.js
if(options.location !== '') {
        weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';
      } else if(options.woeid !== '') {
        weatherUrl += 'select * from weather.forecast where woeid='+options.woeid+' and u="'+options.unit+'"';
      } else {
        options.error({message: "Could not retrieve weather due to an invalid location."});
        return false;
      }

_____________________________________________________________________
main.js
$(document).ready(function() {
    navigator.geolocation.getCurrentPosition(function(position) {
        loadWeather(position.coords.latitude, position.coords.longitude);
    });
});


function loadWeather(location, woeid) {

        $.simpleWeather({
            location: '(' + location + ',' + woeid + ')',
            woeid: "",
....

**Comment by robschwartz** [comment]
Thanks! Hopefully it works.

**Comment by Chimit** [comment]
Need a minified version.

**Comment by TheAmeoba** [comment]
I got around the issue by Removing my location value of "Sydney, AU" and instead using the woeid of 1105779
Error must lie in their location functions

**Comment by billyrudi** [comment]
elso for me this solve my problem.
$.simpleWeather({
    location: '(' +  arguments[1] + ')',

**Comment by pparo** [comment]
I could'nt get around the issue yet. Still getting the channel error.I used @VitalyNikolaev solution together with the new js from @robschwartz

**Comment by joejoe9982** [comment]
@balazsegyed: nice hint, but won't work with SSL :(
@VitalyNikolaev: Won't work with lat/long either :(

**Comment by joejoe9982** [comment]
Any solution for lat/long?

**Comment by joejoe9982** [comment]
@rwebler: (merging  jquery.simpleWeather.js) won't work with lat/long either. :(

**Comment by billyrudi** [comment]
i have datas with this changes

 weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';
   
and 

$.simpleWeather({
location: '(' + arguments[1] + ')',

**Comment by ampLocal** [comment]
Here's what worked for me, I have several location pages that call for weather for a single city. I modified the jquery Line #26 as indicated in several replies above. And then opened every index.js file and remove the location: '(' + arguments[1] + ')', string from the js (line 4)

**Comment by frontendcarl** [comment]
@bluesunlite It works for me, thank you so much :)

**Comment by exhtml** [comment]
@billyrudi solution for working with lat/long, thanks very much!

**Comment by bhu1st** [comment]
@rysie 
 
Using geo.places table instead of geo.placefinder solves the issue but that leads to another issue when there are multiple results for given options.location (aka multiple WOEIDs)

SELECT * FROM weather.forecast WHERE woeid IN (SELECT woeid FROM geo.places WHERE text="Ottawa, Canada" limit 1)

Read more here:
http://stackoverflow.com/questions/31185619/why-does-this-yahoo-weather-api-query-not-work

**Comment by GTMaic** [comment]
Ty Guys...
i had that prblem... I replace the line #26 whit this:

weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';

THis work for me :D

**Comment by Chimit** [comment]
Any chances for the official fix?

**Comment by shariqraza** [comment]
@rysie solutions works perfectly for now. Simply replace the line #26 with his solution.

**Comment by evenezianoMSA** [comment]
Could someone assist me to verify something real quick.  Does this error cause the widget to completely not display?  Or will it display with an error on the widget?  I am using this on SharePoint and for me the widget completely disappeared from where it was placed.  My error is basically what is occurring on the demo of SimplyWeather's site.  The weather/text is completely missing.

I also tried the workaround that was mentioned for line 26 (removing gflags) with no success. Any help would be greatly appreciated.

**Comment by shariqraza** [comment]
@evenezianoMSA The error causes the widget to not display. Download the latest version of the simpleWeather.js file and after replacing the said line in code with the solution, try initializing the widget by giving location names not coordinates  e.g

 jQuery.simpleWeather({
   location: 'Isfahan, Iran',

**Comment by evenezianoMSA** [comment]
@shariqraza Thanks for the quick response.  We are currently using the "simpleWeather.min.js" file... Does that make any difference?

**Comment by shariqraza** [comment]
@evenezianoMSA  It shouldn't. But to correctly replace the code use the un-minfied file from repo here: https://raw.githubusercontent.com/monkeecreate/jquery.simpleWeather/master/jquery.simpleWeather.js

Repace the code on Line 26 with:

weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';

**Comment by evenezianoMSA** [comment]
@shariqraza Much appreciated sir.  I will give this a shot and see how it goes.

**Comment by trustedjohn** [comment]
@shariqraza This worked for me thanks!

**Comment by CarlosRGL** [comment]
works for me changing line 26 :) thanks!!!!

**Comment by EriQ** [comment]
Changing line 26 to 

weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';

works for Chrome, but there is still nothing displayed in Firefox, or Edge. Has anyone else had this problem?

**Comment by evenezianoMSA** [comment]
@shariqraza Just wanted to let you know that because of your help, I got it to work.  Thank you sir, much appreciated.

**Comment by jpggvilaca** [comment]
"cannot ready property channel of null" , changing that line still produces this error instead of the 'results' of undefined.

**Comment by axelboberg** [comment]
Still doesn't work for me. I've used the plugin in production so a fix soon would be very helpful!

**Comment by msoler8785** [comment]
Use the indexed version of geo.places property.  This will limit you to one result.  The following change to line 26 got everything working for me.

```javascript
weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+options.location+'") and u="'+options.unit+'"';
```
Yahoo also has a YQL query tester here which was helpful:

https://developer.yahoo.com/weather/

**Comment by tom-daly** [comment]
i believe that people might still be confused. The reverse geocoding from Yahoo is still out so if you are using Lat/Lon the solution won't work no matter what fixes you try above. 

I am stuck right now using lat/long because we first use the geolocation from the web browser and as a back I then use lat/long from IP. So I must use lat/long. 

My Workaround - Prior to calling simpleWeather I take my lat/long and send it to https://www.openstreetmap.org then pass back the display name to simpleWeather location. Below code is an example.

** You must also update use the fix from above **
`weatherUrl += 'select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="'+options.location+'") and u="'+options.unit+'"';`

```javascript
  $.ajax({
                    type: "GET",
                    dataType: 'json',
                    data: {
                        'format': 'json',
                        'lat': location.split(',')[0],
                        'lon': location.split(',')[1],
                        'addressdetails': '0'
                    },
                    url: 'http://nominatim.openstreetmap.org/reverse',
                    success: function (address) {
                        //GO CALL SIMPLEWEATHER with address.display_name as location
$.simpleWeather({
	location: address.display_name
	unit: 'f',
success: function(weather) {},
error: function(error) {}
});

                    },
                    error: function (error) {
                        //HANDLE FAIL
                    }
                });

```

**Comment by ygalanter** [comment]
@andretf and everybody THANK YOU! Really helped me a big deal to resolve the same issue in my Pebble watchfaces.

**Comment by jukhadar** [comment]
Thanks all of you 
@shariqraza it works

**Comment by jpggvilaca** [comment]
@msoler8785 , i still get the 'channe of null' error...

**Comment by andretf** [comment]
@tom-daly surrounding geolocation with parentheses works for me.

For those who have problems in catching error see my pull #185 for fixing the error handling.

For dynamic location type, where location can be an address, a lat/long or whatever, you could give a try to my solution b9a8a34 in my fork.

**Comment by drumminhands** [comment]
As a user, if you stop using location lookups, but instead use the woeid, all is well. http://woeid.rosselliot.co.nz/lookup/ 

If you don't have a dynamic search, but a fixed location to display, this is an alternative temporary solution.

**Comment by JWiersema** [comment]
Thanks @tom-daly !

**Comment by aferrerdev** [comment]
I had used this yahoo developer url to solve and test my url errors, it should help to test your weatherUrls too.
https://developer.yahoo.com/weather/

My lines 26 to 35 in jquery.simpleWeather.js:
```
 var query, weatherUrl;
      if(options.location !== '') {
        query = 'select * from weather.forecast where woeid in (select woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';
        weatherUrl = 'https://query.yahooapis.com/v1/public/yql?q='+query+'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys';
      } else if(options.woeid !== '') {
        query = 'select * from weather.forecast where woeid='+options.woeid+' and u="'+options.unit+'"';
        weatherUrl = 'https://query.yahooapis.com/v1/public/yql?q='+query+'&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys';
      } else {
        options.error({message: "Could not retrieve weather due to an invalid location."});
        return false;
      }
```

**Comment by christopherprins** [comment]
Thank you kindly @andretf, [b9a8a34 ](https://github.com/monkeecreate/jquery.simpleWeather/commit/b9a8a342ad7a513156e9122864559bd27b47205b) worked for me.

**Comment by islanddog** [comment]
Amazing job @aferrerdev . Saved my Digital Signage from looking boring.

**Comment by geerlingguy** [comment]
Also working for me for either location by name or by coordinates using @andretf's fix in https://github.com/monkeecreate/jquery.simpleWeather/commit/b9a8a342ad7a513156e9122864559bd27b47205b — note that I'm still running into various Yahoo API errors like 'City not found' after the geolookup succeeds, etc., but I'm handling that by falling back to a default woeid for now.

**Comment by demonicinn** [comment]
not workin

**Comment by fleeting** [comment]
I have released an update to simpleWeather that fixes the issue. If anybody cares to test it out on their own setup that would be great. I did some testing with the demos and didn't have any issues. The cdn copy is still pending the refresh so you will need to download the file from the repo directly.

Thanks to everybody who helped debug the issues and fixes. It turns out Yahoo has completely removed the `geo.placefinder` API point that I was using before (thanks for that Yahoo). It now uses `geo.places`. I'll leave this open for a day or two.

**Comment by Mikeysauce** [comment]
lol very weird that I'm in the process of updating my site when you push out this fix. Tried everything in the comments above to no avail but your fix immediately sorted it with a ctrl v. (ps this is with 5 different locations all pulling in using Lat/Long)

**Comment by geerlingguy** [comment]
@fleeting - Thanks so much for the new release; I was _just_ about to push up a patched version of the library when I noticed you published an update. It works great for my use case: use user geolocation coordinates, fallback to a specific woeid. Both work great, and I tested a few location names as well.

**Comment by ygalanter** [comment]
Was getting a more generic location than I wanted using the query above, [so modified it slightly](http://codecorner.galanter.net/2016/01/25/fixing-problem-with-yahoo-geolocation-service#update1)

**Comment by steintraci** [comment]
I still can't get mine to work, It won't update.  With all of the conversations above, its hard to tell what exactly am I supposed to do about this?  Do I can the whole thing and start over by uploading the new files or what?  I cant follow what you are asking us to do?

**Comment by steintraci** [comment]
OOPS nevermind it works now :) ThANK YOU!

**Comment by tk1087** [comment]
it stopped working for me again just about 20mins ago... it was working fine but now I see that it's broken even on this site.

**Comment by christopherprins** [comment]
Same as @tk1087 . Very recently stopped working.

> Uncaught TypeError: Cannot read property 'results' of undefined

**Comment by tk1087** [comment]
and of course now it starts working again, it just fixed itself.

**Comment by christopherprins** [comment]
Ditto.

**Comment by fleeting** [comment]
The demos are currently working for me so I would need to see some code or links to what isn't working to be of any hell.

**Comment by DukeBaird** [comment]
Also working for me - Thanks for the fix

**Comment by ecdcrew** [comment]
> The demos are currently working for me so I would need to see some code


$.simpleWeather({  location: 'Austin, Tx', ...... WORKS
$.simpleWeather({  location: 'Bridgetown, Barbados', ...... DOES NOT

Try in codepen

**Comment by steintraci** [comment]
We got it working….thanks.

**Comment by ecdcrew** [comment]
Seems like international (non-us) weather is NOT working. So yours may be working, but international is not.

**Comment by andyades** [comment]
Anyone else just lose it again? Getting the "THERE WAS A PROBLEM RETRIEVING THE LATEST WEATHER INFORMATION." in the codepen too.

**Comment by geerlingguy** [comment]
@andyades - Getting the same here, today. I wonder if it's just Yahoo being flaky again, or if they're changing their API yet again.

**Comment by steintraci** [comment]
That's great it's happening on mine too.

**Comment by fleeting** [comment]
Looks like Yahoo's weather API is down right now. Their YQL console is returning an error. https://developer.yahoo.com/yql/console/#h=select+*+from+weather.forecast+where+woeid%3D2367105

**Comment by ashwinkshenoy** [comment]
Hey guys,
International (Non-US) places are not working, as its not showing the city name correctly with latitude-longitude.

I slightly modified the query of line 25 to this:
`weatherUrl += 'select * from weather.forecast where woeid in (select admin2.woeid from geo.places where text="'+options.location+'" limit 1) and u="'+options.unit+'"';`

Instead of using woeid, I used **admin2.woeid** and it returns exact city place and not rooftop (shop/mall/place name).

in .js
`navigator.geolocation.getCurrentPosition(function(position) {
    loadWeather(position.coords.latitude, position.coords.longitude);
  });

$.simpleWeather({
    location: '(' + location + ',' + woeid + ')',
.......`

one of my example: with lat long (13.0120147,77.6729956)

Full Url
[https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.places%20where%20text%3D%22(13.0120147,77.6729956)%22&format=json](https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.places%20where%20text%3D%22(13.0120147,77.6729956)%22&format=json)

Customised Url :
[https://query.yahooapis.com/v1/public/yql?q=select%20admin2.woeid%20from%20geo.places%20where%20text%3D%22(13.0120147,77.6729956)%22&format=json](https://query.yahooapis.com/v1/public/yql?q=select%20admin2.woeid%20from%20geo.places%20where%20text%3D%22(13.0120147,77.6729956)%22&format=json)

the name is coming - "F-Square" but it should come Bangalore(city) in India.
hence I am using admin2.woeid

Some people also suggested using locality1 instead of admin2, but locality 1 is not available everywhere..

By the way - all this is to get the right city.
@fleeting - Do let me know if using this method is the right way.

**Comment by fleeting** [comment]
Yahoo's API seems to be back up and working. I'm closing this as the main issue in this thread has been fixed. Any other problems just create a new issue.
